### ISSUE TITLE
`wholes` and `parts` are undefined

### ISSUE THREAD

**Issue by LegionMammal978** [pochmann/regex-golf#1]
See the title. In `further_improvements.py`, the function uses `wholes | parts | pairs`.

**Comment by pochmann** [comment]
They are defined. Probably in the `...` part of the function (I can't find it anymore, I guess Peter got rid of it during a rewrite of his page). Those code snippets are what the filename suggests, small improvements, and I showed only the relevant parts.

**Comment by LegionMammal978** [comment]
However, the entire main function seems to be dependent on it. If you aren't going to post a working program, why post it at all?
